version: '3'

volumes:
  dc-data:

networks:
  dc-net:

services:
  dc-db:
    image: stackupiss/northwind-db:v1
    volumes:
      - dc-data:/var/lib/mysql
    networks:
      - dc-net
  dc-app:
    image: stackupiss/northwind-app:v1
    environment:
      - DB_HOST=dc-db
      - DB_USER=root
      - DB_PASSWORD=changeit
    networks:
      - dc-net
    ports:
      - 8090:3000
