---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bggdb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: bggdb-po
      app: bggdb
  template:
    metadata:
      name: bggdb-po
      labels:
        name: bggdb-po
        app: bggdb
    spec:
      containers:
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bggdb
spec:
  type: ClusterIP
  selector:
    name: bggdb-po
    app: bggdb
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bggapp
spec:
  replicas: 3
  selector:
    matchLabels:
      name: bggapp-po
      app: bggapp
  template:
    metadata:
      name: bggapp-po
      labels:
        name: bggapp-po
        app: bggapp
    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: BGG_DB_USER
          value: root
        - name: BGG_DB_HOST
          value: bggdb-svc.bggns.svc.cluster.local
        - name: BGG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bggdb-secret
              key: db_password
        readinessProbe:
          httpGet: 
            path: /healthz
            port: 3000
          timeoutSeconds: 5
        livenessProbe:
          httpGet: 
            path: /healthz
            port: 3000
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bggapp
spec:
  type: LoadBalancer
  selector:
    name: bggapp-po
    app: bggapp
  ports:
  - port: 8080
    targetPort: 3000



