# demonstrating multi-stage building (final container does not need go compiler!)

ARG ALPINE_VERSION=3.17
ARG GO_VERSION=1.20-alpine${ALPINE_VERSION}

FROM golang:${GO_VERSION} AS builder

WORKDIR /app

COPY go.mod .
COPY go.sum .
COPY main.go .

RUN go build -o main .

FROM alpine:${ALPINE_VERSION}

WORKDIR /app

COPY --from=builder /app/main .
COPY public public
COPY templates templates

ENV PORT=3000 INSTANCE_NAME="gobear" GIN_MODE=release

EXPOSE ${PORT}

ENTRYPOINT /app/main